name: CI/CD Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t eleicoes-backend .

      # Push Docker Image to Docker Hub (Opcional, se desejar armazenar a imagem)
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # - name: Push Docker Image
      #   run: |
      #     docker tag eleicoes-backend username/eleicoes-backend:latest
      #     docker push username/eleicoes-backend:latest

      # Deploy via SCP
      - name: Copy Files via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: 3.101.81.146
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "./"
          target: "~/EleicoesVirtual-back-end/"

      # Run deployment commands via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 3.101.81.146
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/EleicoesVirtual-back-end/
            sudo docker stop eleicoes-backend || true
            sudo docker rm eleicoes-backend || true
            sudo docker build -t eleicoes-backend .
            sudo docker run -d -p 8080:8080 --name eleicoes-backend eleicoes-backend

