name: CI/CD Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Cria o arquivo JSON a partir do segredo
      - name: Create Firebase Credentials File
        run: |
          echo ${{ secrets.FIREBASE_CREDENTIALS_BASE64 }} | base64 --decode > eleicoesvirtual-firebase-adminsdk-baotz-3973687bb4.json

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build --no-cache -t eleicoes-backend .

      # Limpar o sistema Docker após o build para liberar espaço
      - name: Clean Docker system
        run: |
          docker system prune -f --volumes

      # Deploy via SCP (código sem o arquivo JSON)
      - name: Copy Files via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: 3.101.81.146
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "./"
          target: "/home/ec2-user/EleicoesVirtual-back-end/"
          debug: true

      # Run deployment commands via SSH (usando o JSON local na VM)
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 3.101.81.146
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/EleicoesVirtual-back-end/
            # Verificar e remover contêiner anterior
            if [ $(docker ps -q -f name=eleicoes-backend) ]; then
              sudo docker stop eleicoes-backend
              sudo docker rm eleicoes-backend
            fi
            # Build e run do novo contêiner (sem o arquivo JSON no build)
            sudo docker build -t eleicoes-backend .
            sudo docker run -d -p 8081:8081 --name eleicoes-backend \
              -v /home/ec2-user/EleicoesVirtual-back-end/eleicoesvirtual-firebase-adminsdk-baotz-3973687bb4.json:/app/credentials/eleicoesvirtual-firebase-adminsdk-baotz-3973687bb4.json \
              -e GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/eleicoesvirtual-firebase-adminsdk-baotz-3973687bb4.json \
              eleicoes-backend
